apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      serviceAccountName: nginx
      initContainers:
      - name: init-svid
        args:
        - --mode=init
        - --workload-api-socket=/var/run/spire/agent.sock
        - --pod-spiffe-id=spiffe://example.org/workload/nginx
        - --svid-path=/var/run/secret/nginx
        image: hiyosi/pod-svid-helper:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /var/run/spire
          readOnly: false
        - name: svid-dir
          mountPath: /var/run/secret/nginx
      containers:
      - name: nginx
        image: nginx:1.17.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: svid-dir
          mountPath: /var/run/secret/nginx
      - name: refresh-svid
        args:
        - --mode=refresh
        - --workload-api-socket=/var/run/spire/agent.sock
        - --pod-spiffe-id=spiffe://example.org/workload/nginx
        - --svid-path=/var/run/secret/nginx
        image: hiyosi/pod-svid-helper:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /var/run/spire
          readOnly: false
        - name: svid-dir
          mountPath: /var/run/secret/nginx
      volumes:
        - emptyDir: {}
          name: svid-dir
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
