language: go

go:
  - 1.13.x
  - 1.14.x
  - master

script:
  - make test
  - make build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    make docker-push ;
    fi
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    TAG=$TRAVIS_TAG make docker-push-tag ;
    fi
